name: ERC Registry Indexer

on:
  push:
    branches:
      [
        1081-erc-registry-phase-2-add-an-option-to-execute-the-indexing-tool-as-a-github-dispatch-workflow,
      ]
  workflow_dispatch:
    inputs:
      HEDERA_NETWORK:
        description: 'Target Hedera network (e.g., previewnet, testnet, mainnet).'
        required: true
      MIRROR_NODE_URL:
        description: 'Mirror node base URL (e.g., https://testnet.mirrornode.hedera.com).'
        required: true
      STARTING_POINT:
        description: 'Starting point for indexing (e.g., a specific block number). Leave empty to start from the beginning.'
        required: false

jobs:
  index-and-update:
    name: Index ERC Contracts and Update Registry
    runs-on: smart-contracts-linux-large
    env:
      INDEXER_PATH: ./tools/erc-repository-indexer/erc-contract-indexer

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive

      - name: Use Node.js [20]
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
          #cache: npm Disabling this because it causes the workflow to hang and eventually timeout

      - name: Set Environment Variables
        run: |
          echo "HEDERA_NETWORK=previewnet" >> ${{ env.INDEXER_PATH }}/.env
          echo "MIRROR_NODE_URL=https://previewnet.mirrornode.hedera.com" >> ${{ env.INDEXER_PATH }}/.env
          echo "STARTING_POINT=${{ github.event.inputs.STARTING_POINT }}" >> ${{ env.INDEXER_PATH }}/.env

      - name: Install Dependencies
        run: |
          cd ${{env.INDEXER_PATH}}
          npm install

      - name: Start ERC Registry Indexer
        run: |
          cd ${{env.INDEXER_PATH}}
          npm start

      - name: Import GPG Key
        id: gpg_importer
        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v6.1.0
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_KEY_CONTENTS }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}

      - name: Get Current Date
        id: current_date
        run: echo "CURRENT_DATE=$(date -u +"%m-%d-%Y")" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7.0.5
        with:
          branch: ERC-Registry-Periodical-Update/${{ github.run_id }}
          commit-message: 'chore: update ERC Registry with latest ERC tokens on ${{github.event.inputs.HEDERA_NETWORK}}'
          committer: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          author: ${{ steps.gpg_importer.outputs.name }} <${{ steps.gpg_importer.outputs.email }}>
          delete-branch: true
          signoff: true
          title: 'chore: update ERC Registry with latest tokens on ${{github.event.inputs.HEDERA_NETWORK}}'
          body: >
            **Description**:  

            This PR provides a periodic update for the ERC Registry, including the latest ERC-20 and ERC-721 tokens indexed from Hedera ${{ github.event.inputs.HEDERA_NETWORK }} as of ${{ env.CURRENT_DATE }}.


            Fixes #
          labels: 'internal'
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          assignees: 'swirlds-automation'
